import "./globals.css";
// import { Inter } from "next/font/google";

export const metadata = {
  title: "Flavour Forge",
  description: "Generated by create next app",
};

// const inter = Inter({ subsets: [Latin], weight: [400, "700"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
